Mesh: 
  - 
    - 
      SequencingElement: 
        - 
          start_after_cycle_number: 4294967295
          pattern_index: 1
        - 
          start_after_cycle_number: 3232
          pattern_index: 3
      ControlPatternGenerator: 
        - 
          pe_control: GEMM_OS_PROP
          repeat_for_n_cycles: 69
          next_index: 1
        - 
          pe_control: GEMM_OS_COMP
          repeat_for_n_cycles: 16
          next_index: 0
    - 
      SequencingElement: 
        - 
          start_after_cycle_number: 0
          pattern_index: 0
        - 
          start_after_cycle_number: 0
          pattern_index: 0
      ControlPatternGenerator: 
        - 
          pe_control: GEMM_OS_PROP
          repeat_for_n_cycles: 16
          next_index: 1
        - 
          pe_control: GEMM_OS_COMP
          repeat_for_n_cycles: 16
          next_index: 0
  - 
    - 
      SequencingElement: 
        - 
          start_after_cycle_number: 0
          pattern_index: 0
        - 
          start_after_cycle_number: 0
          pattern_index: 0
      ControlPatternGenerator: 
        - 
          pe_control: GEMM_OS_PROP
          repeat_for_n_cycles: 16
          next_index: 1
        - 
          pe_control: GEMM_OS_COMP
          repeat_for_n_cycles: 16
          next_index: 0
    - 
      SequencingElement: 
        - 
          start_after_cycle_number: 0
          pattern_index: 0
        - 
          start_after_cycle_number: 0
          pattern_index: 0
      ControlPatternGenerator: 
        - 
          pe_control: GEMM_OS_PROP
          repeat_for_n_cycles: 16
          next_index: 1
        - 
          pe_control: GEMM_OS_COMP
          repeat_for_n_cycles: 16
          next_index: 0
